version: '3.2'
services:
  jenkins:
    build:
      dockerfile: Dockerfile.jenkins
      context: jenkins
    volumes:
    - ./jenkins/home:/var/jenkins_home
    - ./.git:/repo.git
    ports: [ '8080:8080' ]
    networks: [ 'monorepo-net' ]

  jenkins-worker:
    build:
      dockerfile: Dockerfile.worker
      context: jenkins
    privileged: true
    volumes:
    - ./.git:/repo.git
    - /var/run/docker.soc:/var/run/docker.sock
    networks: [ 'monorepo-net' ]
    command: 'tail -f /dev/null'

networks:
  monorepo-net:
