version: '3.2'
services:
  jenkins:
    build:
      dockerfile: Dockerfile.jenkins
      context: jenkins
    volumes:
    - ./jenkins/home:/var/jenkins_home
    - ./.git:/repo.git
    ports: [ '8080:8080' ]
    networks: [ 'monorepo-net' ]

  jenkins-worker:
    build:
      dockerfile: Dockerfile.worker
      context: jenkins
    volumes:
    - ./.git:/repo.git
    - /var/run/docker.sock:/var/run/docker.sock
    networks: [ 'monorepo-net' ]
    entrypoint: '/bin/bash -c'
    command:
    - |
      while true; do
        wget http://jenkins:8080/jnlpJars/agent.jar
        if [ $$? = 0 ]; then break; fi;
        sleep 7s;
      done
      CRUMB=$$(curl -u "jenkins:jenkins" 'http://jenkins:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)')
      SECRET=$$(curl -L -s -u jenkins:jenkins -H "$${CRUMB}" -X GET http://jenkins:8080/computer/worker/slave-agent.jnlp \
        | sed "s/.*<application-desc main-class=\"hudson.remoting.jnlp.Main\"><argument>\([a-z0-9]*\).*/\1/"
      )
      echo "Secret is: $${SECRET}"
      java -jar agent.jar -jnlpUrl http://jenkins:8080/computer/worker/slave-agent.jnlp -secret $$SECRET -workDir "/tmp"

networks:
  monorepo-net:
